services:
  minimin:
    image: ghcr.io/quonaro/minimin:latest
    ports:
      - "8080:8081"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:ro
      - ${MC_SERVERS_HOST_DIR}:/app/servers
      - ./data:/app/data
    env_file:
      - .env
    restart: unless-stopped
